apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aninaka-api
  namespace: aninaka
spec:
  secretName: aninaka-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.aninaka-api.net"
